### PR TITLE
lab4

### PR DESCRIPTION
**Pull request by IKdotShark**
# Remake with react from [lab3](https://github.com/IKdotShark/WebProg/pull/6)
- [x] exceed_all_exp (woman)
- [x] earlyAccessBtn
- [x] blog
- [x] end

# Tests
- [x] 4k - 2560px
- [x] Laptop L - 1440px
- [x] Laptop - 1024px
- [x] Tablet - 768px
- [x] Mobile L - 425px
- [x] Mobile M - 375px
- [x] Mobile S - 320px

### CODE REVIEW

**Review by IKdotShark — COMMENTED** [review]
All should be okey,  @KuroshiXD good work, cowboy 🤠

**Comment by IKdotShark** [comment]
<h1><p align="center">WE DID IT 🍺. CHEERS 🍻.</p><h1>

<p align="center">
  Cheers
</p>

<h1><p align="center">Now need to fix 😭  Or not 😏</p><h1>

<p align="center">
  Cheers
</p>

**Comment by IKdotShark** [comment]
<h1> <p align = "center"> As I think didn't need to fix </p> </h1>

**Comment by KuroshiXD** [comment]
<p align="center">
  Описание изображения
</p>
<h1 align="center">It's over</h1>

**Comment by memedea1er** [comment]
<h1 align="center">relax</h1>
<p align="center">
  Описание изображения
</p>

**Pull request merged**
